Scp/image registry config
charmed-kubernetes/charm-kube-ovn pull request #14
Opened 2022-06-30 17:43 UTC by stonepreston

Changes the registry config option to be named image-registry to align with other charms. The default is now blank. If the config option is left blank, the charm will grab the image-registry sent by the control plane charm over the CNI relation. This data is distributed among kube-ovn units via a peer relation. Depends on [this PR](https://github.com/juju-solutions/interface-kubernetes-cni/pull/12) that adds the image-registry to the CNI relation, [this PR](https://github.com/charmed-kubernetes/charm-kubernetes-control-plane/pull/231) that modifies the control plane charm to send the data over the relation, as well as [this PR](https://github.com/charmed-kubernetes/charm-kube-ovn/pull/11) since I branched off of adam's work since it was not yet merged.

2022-06-30 21:09 UTC, addyess requested changes
No issue with any of the logic, just some suggestions regarding a few of the method names

2022-06-30 21:09 UTC, addyess commented on src/charm.py
> +                relation.data[self.unit][peer_relation_data_key] = cni_data
this method, i understand the reasoning behind it.  It prevents two copies of what's effectively "repeat this data blob across the kube-ovn peers

what if you instead just wrote a method:

```python
def cni_to_kube_ovn(event):
   for key in ["service-cidr", "image-registry"]:
      cni_data = event.relation.data[event.unit].get(key)
      if not cni_data:
          continue
      for relation in self.model.relations["kube-ovn"]:
          relation.data[self.unit][key] = cni_data
```

and later on call it with:

```python 
    def on_cni_relation_changed(self, event):
        self.cni_to_kube_ovn(event)
        ...
```

2022-06-30 21:09 UTC, addyess commented on src/charm.py
> +    def get_peer_data_with_key(self, data_key):
This method is fine with maybe a name change.  But I wouldn't leave the `get_service_cidr(...)` method with a single line statement in it.  Just find `self.get_service_cidr()` and replace with `self.kube_ovn_peer_data("service-cidr")`.  

Be glad you didn't let me write this or i'd feature creep some object in there that holds all the logic for handling the relation.

```suggestion
    def kube_ovn_peer_data(self, key):
```

2022-06-30 21:34 UTC, addyess approved these changes
🚀 🍰 LGTM!

2022-07-05 15:08 UTC, Cynerva approved these changes
LGTM

2022-07-05 15:39 UTC, merged